#!/usr/bin/env python3
"""
Gaza Whiteboard Animation - Professional Documentary Style
=========================================================

This script creates a high-quality whiteboard-style animation
of the Gaza Strip map, suitable for educational and documentary content.

Usage:
    manim -pql scenes/gaza_whiteboard.py GazaWhiteboardMap     # Preview (480p)
    manim -pqh scenes/gaza_whiteboard.py GazaWhiteboardMap     # High quality (1080p)
    manim -pqk scenes/gaza_whiteboard.py GazaWhiteboardMap     # 4K quality

Author: Generated by Claude AI
License: MIT
"""

from manim import *
import numpy as np
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.map_data import GAZA_COORDINATES, GAZA_CITIES, MEDITERRANEAN_BOUNDS
from utils.colors import WHITEBOARD_COLORS, SKETCH_PARAMS
from utils.sketch_effects import (
    SketchyPolygon,
    MarkerText,
    create_drawing_animation,
    create_writing_animation
)


class GazaWhiteboardMap(Scene):
    """
    Main scene: Animated whiteboard-style map of Gaza Strip.
    """

    def construct(self):
        # === SETUP ===
        self.setup_scene()

        # === ANIMATION SEQUENCE ===
        self.draw_title()
        self.draw_mediterranean_sea()
        self.draw_gaza_map()
        self.add_city_markers()
        self.add_statistics_panel()
        self.final_zoom()

        # Hold final frame
        self.wait(3)

    def setup_scene(self):
        """Configure scene settings for whiteboard style."""
        self.camera.background_color = WHITEBOARD_COLORS['background']

    def draw_title(self):
        """Animate the title appearing."""
        title = Text(
            "Gaza Strip",
            font_size=48,
            color=WHITEBOARD_COLORS['marker_black'],
            weight=BOLD
        ).to_edge(UP, buff=0.5)

        subtitle = Text(
            "Geographic Overview",
            font_size=24,
            color=WHITEBOARD_COLORS['text_secondary']
        ).next_to(title, DOWN, buff=0.2)

        # Underline
        underline = Line(
            start=title.get_left() + DOWN * 0.3,
            end=title.get_right() + DOWN * 0.3,
            color=WHITEBOARD_COLORS['marker_blue'],
            stroke_width=3
        )

        self.play(Write(title), run_time=1.5)
        self.play(
            Write(subtitle),
            Create(underline),
            run_time=1
        )
        self.wait(0.5)

    def draw_mediterranean_sea(self):
        """Draw and animate the Mediterranean Sea."""
        # Sea area (left side of screen)
        sea = Rectangle(
            width=5,
            height=8,
            color=WHITEBOARD_COLORS['sea_blue'],
            fill_color=WHITEBOARD_COLORS['sea_light'],
            fill_opacity=0.3,
            stroke_width=0
        ).move_to(LEFT * 4.5)

        # Wave lines for visual effect
        waves = VGroup()
        for i in range(5):
            wave = FunctionGraph(
                lambda x: 0.1 * np.sin(3 * x + i),
                x_range=[-2.5, 0],
                color=WHITEBOARD_COLORS['sea_blue'],
                stroke_width=2,
                stroke_opacity=0.5
            ).shift(LEFT * 4.5 + UP * (i - 2) * 1.5)
            waves.add(wave)

        # Sea label
        sea_label = Text(
            "Mediterranean Sea",
            font_size=20,
            color=WHITEBOARD_COLORS['sea_blue']
        ).rotate(PI/2).move_to(LEFT * 6)

        self.play(FadeIn(sea), run_time=1.5)
        self.play(
            *[Create(wave) for wave in waves],
            Write(sea_label),
            run_time=1.5,
            lag_ratio=0.2
        )
        self.wait(0.5)

    def draw_gaza_map(self):
        """Draw the Gaza Strip map with hand-drawn effect."""
        # Create the main map polygon
        gaza_map = SketchyPolygon(
            *GAZA_COORDINATES,
            color=WHITEBOARD_COLORS['marker_black'],
            fill_color=WHITEBOARD_COLORS['land_beige'],
            fill_opacity=0.4,
            stroke_width=SKETCH_PARAMS['stroke_width_thick'],
            roughness=0.02
        ).shift(RIGHT * 1)

        # Border highlight (red dashed line for emphasis)
        gaza_border = SketchyPolygon(
            *GAZA_COORDINATES,
            color=WHITEBOARD_COLORS['border_red'],
            stroke_width=2,
            stroke_opacity=0.7,
            fill_opacity=0,
            roughness=0.01
        ).shift(RIGHT * 1)

        # Gaza label
        gaza_label = Text(
            "GAZA",
            font_size=40,
            color=WHITEBOARD_COLORS['marker_black'],
            weight=BOLD
        ).move_to(RIGHT * 1)

        # Animate drawing
        self.play(
            Create(gaza_map),
            run_time=3,
            rate_func=rate_functions.ease_in_out_sine
        )
        self.play(
            Create(gaza_border),
            run_time=1.5
        )
        self.play(
            Write(gaza_label),
            run_time=1
        )

        # Store for later reference
        self.gaza_map = gaza_map
        self.gaza_label = gaza_label

    def add_city_markers(self):
        """Add city markers and labels."""
        city_markers = VGroup()
        city_labels = VGroup()

        cities_to_show = ['gaza_city', 'khan_yunis', 'rafah', 'deir_balah']

        for city_key in cities_to_show:
            city = GAZA_CITIES[city_key]
            pos = np.array(city['pos']) + RIGHT * 1  # Offset to match map

            # City dot
            dot = Dot(
                point=pos,
                color=WHITEBOARD_COLORS['marker_red'],
                radius=0.1
            )

            # City label
            label = Text(
                city['name'],
                font_size=16,
                color=WHITEBOARD_COLORS['text_primary']
            ).next_to(dot, RIGHT, buff=0.1)

            city_markers.add(dot)
            city_labels.add(label)

        # Animate cities appearing
        self.play(
            *[GrowFromCenter(marker) for marker in city_markers],
            run_time=1,
            lag_ratio=0.2
        )
        self.play(
            *[FadeIn(label, shift=RIGHT * 0.2) for label in city_labels],
            run_time=1,
            lag_ratio=0.15
        )
        self.wait(0.5)

    def add_statistics_panel(self):
        """Add an info panel with key statistics."""
        # Panel background
        panel = RoundedRectangle(
            width=3.5,
            height=3,
            corner_radius=0.2,
            color=WHITEBOARD_COLORS['shadow'],
            fill_color=WHITE,
            fill_opacity=0.9,
            stroke_width=2
        ).to_corner(DR, buff=0.5)

        # Statistics
        stats = VGroup(
            Text("Key Facts", font_size=20, color=WHITEBOARD_COLORS['marker_blue'], weight=BOLD),
            Text("Area: 365 km2", font_size=16, color=WHITEBOARD_COLORS['text_primary']),
            Text("Length: 41 km", font_size=16, color=WHITEBOARD_COLORS['text_primary']),
            Text("Width: 6-12 km", font_size=16, color=WHITEBOARD_COLORS['text_primary']),
            Text("Coastline: 40 km", font_size=16, color=WHITEBOARD_COLORS['text_primary']),
        ).arrange(DOWN, aligned_edge=LEFT, buff=0.25)
        stats.move_to(panel.get_center())

        self.play(FadeIn(panel), run_time=0.5)
        self.play(
            *[Write(stat) for stat in stats],
            run_time=2,
            lag_ratio=0.3
        )
        self.wait(1)

    def final_zoom(self):
        """Zoom in on the map for emphasis."""
        self.play(
            self.camera.frame.animate.scale(0.75).move_to(self.gaza_map),
            run_time=2,
            rate_func=rate_functions.ease_in_out_sine
        )


class GazaTimelineAnimation(Scene):
    """
    Alternative scene: Timeline-based animation showing historical context.
    """

    def construct(self):
        self.camera.background_color = WHITEBOARD_COLORS['background']

        # Title
        title = Text(
            "Gaza Strip - Historical Timeline",
            font_size=36,
            color=WHITEBOARD_COLORS['marker_black'],
            weight=BOLD
        ).to_edge(UP)

        self.play(Write(title))

        # Timeline
        timeline = Line(
            LEFT * 6, RIGHT * 6,
            color=WHITEBOARD_COLORS['marker_black'],
            stroke_width=4
        ).shift(DOWN * 2)

        self.play(Create(timeline), run_time=2)

        # Timeline events
        events = [
            ("1948", "Establishment"),
            ("1967", "Occupation"),
            ("1994", "Palestinian Authority"),
            ("2005", "Disengagement"),
            ("2007", "Blockade Begins"),
        ]

        event_group = VGroup()
        for i, (year, event) in enumerate(events):
            x_pos = -5 + i * 2.5

            # Year marker
            dot = Dot(
                point=[x_pos, -2, 0],
                color=WHITEBOARD_COLORS['marker_blue'],
                radius=0.15
            )

            year_text = Text(
                year,
                font_size=18,
                color=WHITEBOARD_COLORS['marker_blue'],
                weight=BOLD
            ).next_to(dot, DOWN, buff=0.2)

            event_text = Text(
                event,
                font_size=14,
                color=WHITEBOARD_COLORS['text_primary']
            ).next_to(year_text, DOWN, buff=0.1)

            event_group.add(VGroup(dot, year_text, event_text))

        for event in event_group:
            self.play(
                GrowFromCenter(event[0]),
                Write(event[1]),
                Write(event[2]),
                run_time=1.5
            )

        self.wait(3)


class MinimalGazaMap(Scene):
    """
    Minimal version: Quick, simple map animation.
    Good for social media or quick explainers.
    """

    def construct(self):
        self.camera.background_color = WHITE

        # Simple map
        gaza = Polygon(
            *GAZA_COORDINATES,
            color=BLACK,
            fill_color="#E8D5B7",
            fill_opacity=0.5,
            stroke_width=4
        )

        label = Text("Gaza", font_size=48, color=BLACK, weight=BOLD)
        label.move_to(gaza.get_center())

        self.play(Create(gaza), run_time=2)
        self.play(Write(label), run_time=1)
        self.wait(2)


# Entry point for direct execution
if __name__ == "__main__":
    print("Run with: manim -pql scenes/gaza_whiteboard.py GazaWhiteboardMap")
    print("For high quality: manim -pqh scenes/gaza_whiteboard.py GazaWhiteboardMap")
